// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0KYCx_mvYAcYdFEpoyJ48ZjqQjg7uT08',
    appId: '1:160499195762:web:f5ff0c757f0c5fc94dc7eb',
    messagingSenderId: '160499195762',
    projectId: 'bookstore-70112',
    authDomain: 'bookstore-70112.firebaseapp.com',
    storageBucket: 'bookstore-70112.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvaUNf4GXoGXrcgHj2KDesiAkICpGk5kQ',
    appId: '1:160499195762:android:05d401dbf492d3dc4dc7eb',
    messagingSenderId: '160499195762',
    projectId: 'bookstore-70112',
    storageBucket: 'bookstore-70112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFGU9fq9Fnav80CIfKtW85aSIHTDG4h-E',
    appId: '1:160499195762:ios:f860a2b1c73cc5644dc7eb',
    messagingSenderId: '160499195762',
    projectId: 'bookstore-70112',
    storageBucket: 'bookstore-70112.appspot.com',
    iosBundleId: 'com.example.bookStore',
  );
}
